twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        my_global_parameter: 'My global parameter from "config/packages/twig.yml" => <b>twig:<b> => <b>globals:</b>'
